export const REPORT_CATEGORIES = {
  PHISHING_IMPERSONATION: [
    "EMAIL_PHISHING",
    "SMISHING",
    "VISHING",
    "BUSINESS_EMAIL_COMPROMISE",
    "FAKE_SUPPORT_SCAM",
    "IMPERSONATION_SCAM"
  ],
  FINANCIAL_FRAUD: [
    "UPI_SCAM",
    "BANK_FRAUD",
    "CREDIT_CARD_FRAUD",
    "REFUND_SCAM",
    "LOTTERY_SCAM",
    "INVESTMENT_SCAM",
    "CRYPTO_SCAM",
    "LOAN_SCAM"
  ],
  ACCOUNT_SECURITY: [
    "ACCOUNT_TAKEOVER",
    "OTP_THEFT",
    "PASSWORD_THEFT",
    "FAKE_LOGIN_PAGE",
    "CREDENTIAL_LEAK",
    "SOCIAL_MEDIA_HACK",
    "ACCOUNT_RECOVERY_SCAM"
  ],
  MARKETPLACE_COMMERCE: [
    "FAKE_DELIVERY_SCAM",
    "MARKETPLACE_SELLER_SCAM",
    "FAKE_SELLER",
    "RENTAL_SCAM",
    "TICKET_SCAM"
  ],
  EMPLOYMENT_SCAMS: ["FAKE_JOB_OFFER"],
  MALWARE_TECH_ABUSE: [
    "MALWARE_LINK",
    "RANSOMWARE",
    "SPYWARE",
    "APK_SCAM",
    "REMOTE_ACCESS_SCAM",
    "QR_SCAM"
  ],
  HARASSMENT_ABUSE: ["HARASSMENT", "EXTORTION", "BLACKMAIL"],
  IDENTITY_DATA_THEFT: ["IDENTITY_THEFT", "DATA_LEAK", "KYC_FRAUD"],
  OTHER: ["SUSPICIOUS_OTHER"]
};

export const REPORT_CATEGORY_VALUES = Object.keys(REPORT_CATEGORIES);
export const REPORT_SUBCATEGORY_VALUES = Object.values(REPORT_CATEGORIES).flat();

export const REPORT_SEVERITY_VALUES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

export const REPORT_SOURCE_CHANNEL_VALUES = [
  "SMS",
  "WHATSAPP",
  "EMAIL",
  "INSTAGRAM",
  "TELEGRAM",
  "PHONE_CALL",
  "WEBSITE",
  "MARKETPLACE",
  "UNKNOWN"
];

export const REPORT_AFFECTED_ASSET_VALUES = [
  "MONEY",
  "BANK_ACCOUNT",
  "SOCIAL_MEDIA_ACCOUNT",
  "EMAIL_ACCOUNT",
  "DEVICE",
  "IDENTITY",
  "OTHER"
];

export const REPORT_STATUS_VALUES = [
  "SUBMITTED",
  "UNDER_REVIEW",
  "INVESTIGATING",
  "NEED_MORE_INFO",
  "RESOLVED",
  "CLOSED",
  "DUPLICATE",
  "FALSE_POSITIVE",
  "ESCALATED",
  "SENSITIVE_HOLD",
  "ARCHIVED"
];

export const REPORT_PUBLIC_STATUS_VALUES = [
  "SUBMITTED",
  "UNDER_REVIEW",
  "INVESTIGATING",
  "NEED_MORE_INFO",
  "RESOLVED",
  "CLOSED"
];

export const REPORT_INTERNAL_STATUS_VALUES = REPORT_STATUS_VALUES.filter(
  (status) => !REPORT_PUBLIC_STATUS_VALUES.includes(status)
);

export const LEGACY_REPORT_CATEGORIES = ["PHISHING", "SCAM", "HARASSMENT", "OTHER"];
export const LEGACY_REPORT_STATUSES = ["PENDING", "REVIEWED", "RESOLVED"];

export const isValidCategorySubcategory = (category, subcategory) => {
  const subcategories = REPORT_CATEGORIES[category];
  if (!subcategories) return false;
  return subcategories.includes(subcategory);
};
